### ISSUE TITLE
Issue with document intelligence and frontend interraction

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-backend#139] opened 2024-09-03 18:22 UTC
## Description  

**Bug Summary:** Since the api keys have been changed, the frontend is not able to use the analyze route.
The swagger route (/apidocs) is able to use it correctly though.
Through some modification to the backend i was able to confirm that the pdf document could be created by the blob storage and was in fact correctly created. I dont have much more information on why it doesnt work. 

**Steps to Reproduce:**  
Use the frontend to send an image to the analyze route ( upload a picture through the capture page and click on the submit button
or use this code snippet to send a picture

**Expected Behavior:**  
The analyze route sends a json in the format of the expected.json (present in the pipeline repo)

**Actual Behavior:**  
An error is sent

**Comment by k-allagbe** [comment] 2024-09-05 19:29
@Youllou I can't reproduce. Do you still observe this on the main branch while using the latest changes in https://github.com/ai-cfia/fertiscan-frontend/pull/220?

**Comment by snakedye** [comment] 2024-09-09 12:16
From the tests I've been doing, the front-end seems to fail **after** the analysis.

@Youllou The route that fails is `POST /inspection`. Can you confirm this on your end?

If that's the case it'd be helpful to see what you're sending to the backend.

**Comment by k-allagbe** [comment] 2024-09-09 12:42
> From the tests I've been doing, the front-end seems to fail **after** the analysis.
> 
> @Youllou The route that fails is `POST /inspection`. Can you confirm this on your end?
> 
> If that's the case it'd be helpful to see what you're sending to the backend.

If there is a problem with /inspection, we should make another issue. And close this one once there's a clear confirmation that /analyze is working as expected.

**Comment by k-allagbe** [comment] 2024-09-12 17:09
Can't reproduce. Closing this. Please @Youllou, reopen if the issue arises again.

**Closed** 2024-09-12 17:09 UTC
Labels: bug
